### PR TITLE
Fix/flutter3

### LINKED ISSUE #315: Compilation errors - Flutter 3.0
Hi, 
I'm using the latest beta of Flutter 2.13.0. and I can't build my app because of errors.

I know this is not ideal using the beta version of flutter and request support for it, but I would kindly ask you to publish a prerelease (dev) version of speech_to_text with fixes for this errors, as this will also happen when 2.13.0 hits stable.

Thanks
```
e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (81, 8): Class 'SpeechToTextPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (627, 5): 'onRequestPermissionsResult' overrides nothing
e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (771, 9): Class 'ChannelResultWrapper' is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (786, 5): 'error' overrides nothing
e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (789, 30): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.
```

### PR DESCRIPTION
**Pull request by atrope**
fixes #315

### CODE REVIEW

**Comment by atrope** [comment]
Hi @sowens-csd I tested on flutter3.
If it does not work on flutter2, 
We could update on pubspec that we need flutter>=3 and dart >=2.17 for this to work

**Review by sowens-csd — APPROVED** [review]
I'll merge this then test on prior Flutter versions.

**Comment by naamapps** [comment]
@sowens-csd in the meantime can you publish a prerelease to pub.dev?

**Comment by sowens-csd** [comment]
5.5.0 is now published to pub.dev. This build seems to work in previous versions of Flutter. Please let me know if there are any issues when you try it.

**Pull request merged**
