### PR TITLE
Update json_serializable package

### PR DESCRIPTION
**Pull request by AlexHartford**
json_serialiazble 3.0.0 -> 4.0.2 to avoid conflicts with null safety updates made to freezed and other packages.

### CODE REVIEW

**Comment by sowens-csd** [comment]
There's a null-safety branch I'm working into update for v2. Would these changes be better made there?

**Comment by AlexHartford** [comment]
Yes - done. Let me know if there's anything else I can do!

**Comment by sowens-csd** [comment]
Thanks for doing this and sorry it took me a while to get to this PR. I think the work that @kaladron has been doing on the null-safety branch has made some of this PR obsolete? 

The one big change that should still get done is to update the JSON dependency, which is where you started. I'll make that change on the null-safety branch and test it out for release. Can you let me know if there's anything else in this PR that I've missed that should get done?

**Comment by AlexHartford** [comment]
Sounds good to me, thanks for the updates!

**Pull request closed without merging**
