### PR TITLE
Update SpeechToTextPlugin.kt

### PR DESCRIPTION
**Pull request by rsydor**
Fix crash on android.

### CODE REVIEW

**Comment by sowens-csd** [comment]
That looks like a great fix, thanks! Do you know under what circumstances the crash happens? Just wondering if there could be other problems with the bluetooth logic I should test for.

**Comment by rsydor** [comment]
We test it on API 33 device. Before 33 was ok.

**Comment by sowens-csd** [comment]
Thanks, good to know. I'll have to try on 33.

**Review by sowens-csd — APPROVED** [review]

**Comment by rsydor** [comment]
I dont use bluetooth with this plugin.

**Pull request merged**
