### PR TITLE
inclusion of the onRmsChanged function to observe frequency changes.

### PR DESCRIPTION
**Pull request by jheimes-silveira**
Notes whether the sound level does not change audio stream.

### CODE REVIEW

**Comment by jheimes-silveira** [comment]
inclusion of the onRmsChanged function to observe frequency changes.
Notes whether the sound level does not change audio stream.

**Comment by jheimes-silveira** [comment]
I'm very happy to contribute, I didn't change the layout of the example to test a new function

**Comment by sowens-csd** [comment]
Looks good. 

Could you make the example main.dart changes a separate PR? Those changes are large and I don't fully understand them. I could then merge the rest of your changes in.

**Comment by sowens-csd** [comment]
I've merged your changes into a new branch, onRmsChanged and then made a few changes. In particular I moved the listener from a separate method to a named parameter of the listen method. Nice changes on the example app, I understand what you did now. 

Unless you have any major changes you'd like to see I'll merge this over to master.

**Pull request merged**
