### PR TITLE
Add '.mixWithOthers' option in audio session category to make speech to text work perfectly when IOS devices are playing audio

### PR DESCRIPTION
**Pull request by wamynobe**
relate to #487 #472

### CODE REVIEW

**Comment by wamynobe** [comment]
I'm currently working on Android side

**Comment by wamynobe** [comment]
I will update in this pr. It will take me awhile to implement because I am reading the documentation 😁 Then check to make sure it will work great in MacOS also. When I finish, I will tag you here for a review. Thank you!

**Comment by wamynobe** [comment]
It is quite weird on android. I can not find any API that set the audio in speech to text side. I tried exoplayer with `isMixMode` option by
```kotlin
exoPlayer.setAudioAttributes(
        new AudioAttributes.Builder().setContentType(C.AUDIO_CONTENT_TYPE_MOVIE).build(),
        !isMixMode);
```
 It worked as I expected. But to the web view case, video or audio is paused all the time when some other features request for audio focus. I have not found any ideas yet.

**Comment by sowens-csd** [comment]
"It is quite weird on android" I could not agree more! 

This is such a useful feature that I think it would be good to get it into a build even if it only supports iOS.  If Android is hard we should probably split it into a separate PR and merge this one. Thoughts?

**Comment by wamynobe** [comment]
@sowens-csd Sure! Let's merge this PR first. I will keep working on the Android platform. Firstly, trying to resolve it from the web view package. I tested it with the package `flutter_video` which was implemented by exoplayer on Android and It worked  perfectly. I think It should be resolved on the web view side.

**Comment by wamynobe** [comment]
@sowens-csd Can you merge this PR first?

**Pull request merged**
