### PR TITLE
Reset lastRegonized in the listen method

### PR DESCRIPTION
**Pull request by cselti**
- resets the `_lastrecognized` in the `listen` method
- more detailed error message handling in ListenFailedException
- fixes parent project path in the demo pubspec.yaml

### CODE REVIEW

**Review by sowens-csd — COMMENTED** [review]
I think the PR title covers just the audio_player_interaction changes. Can you explain the big picture goal of the empty response handling changes?

**Comment by cselti** [comment]
On iOS I don't get error callback like on Android (there is another PR to solve this) when I get empty response and the last recognized word contains the last not empty response - so I unable to detect the empty response.

**Review by sowens-csd — CHANGES_REQUESTED** [review]
Would it solve your problem to set `_lastRecognized=''` in the `listen` method? That way it would still be preserved in cases where a result is recognized during a `listen` but wouldn't have a value otherwise. This could be a breaking change so I want to think a little more about how to roll it out. The docs do say that the value is maintained across a cancel call and reset on listen although the code doesn't seem to do this now.

**Comment by cselti** [comment]
I modified the code to reset the `_lastRecognized` only in the `listen` method. The previously merged iOS error handling also helps to detect the empty response too.

**Review by sowens-csd — COMMENTED** [review]
You changed the error case in the Swift implementation to trigger if `task.error` is not nil or the task reported false for successful completion. Did you find a case where `successfully` was true but there was still an error condition? The change looks okay as I don't see why those two states would contradict each other but if they don't it also shouldn't be needed so I'd like to understand what you learned that caused that change.

**Comment by cselti** [comment]
Yes, that is correct - that condition is not necessary - I have removed it.

**Review by sowens-csd — APPROVED** [review]
Thanks for making the changes, merging now.

**Pull request merged**
