### PR TITLE
Remove init checks for locales

### PR DESCRIPTION
**Pull request by figengungor**
This enables to access locales before initializing SpeechToText. 

Reason: Speech to text feature is optional in my app and I don't want to initialize unless user wants to use this feature. However I would like to show the current locale and locale list to user even though s/he didn't start to use this feature.

### CODE REVIEW

**Review by sowens-csd — CHANGES_REQUESTED** [review]
This looks like a reasonable change but have you checked whether it will work on iOS? We can't remove the initialization check in the plugin without having it work properly on both platforms. That could lead to incorrect behaviour on iOS if it is called without initialization. 

Also, when you are listing locales is it acceptable that they are speech only locales? This method doesn't list all locales available for the device, only those that have speech recognition available for them.

**Comment by sowens-csd** [comment]
I should have also said, thanks for the PR! I do appreciate the contribution.

**Comment by figengungor** [comment]
Nope, I don't have iOS environment to test this right now. Can you test this for iOS? 

Yes, it is acceptable they are speech only locales. I'll only use them for this feature.

If you want I can skip the init check for Android only. Or if you don't have time to test other platforms, that's ok, you can close this merge request and I'll use my fork.

Have a nice day!

**Comment by JekaNS** [comment]
Hi there,

I'm also interested in this feature. So i checked this in my IOS project.

Знімок екрана 2023-06-27 о 23 06 17


In the screenshot, you can see that the execution is stopped at the breakpoint before initialization. And you can see the state of the internal properties _ availableLocales and _currentLocale , but sttInitialized is set to false.

I tested this on an IOS simulator (16.4) and a physical device (16.5.1).

So, for iOS is enough to remove the initialization check in the plugin (Dart part). And there is no need to make any changes to the iOS platform plugin part.

**Review by sowens-csd — APPROVED** [review]
Looks good, thanks for the PR. I had to make one change to support the new Android 33+ check for locales. It means that the locales list will be empty until the user has responded to the permission dialog in the first initialize check.

**Pull request merged**
